version: "2.4"

services:
  image-randomizer-fe:
    container_name: image-randomizer-fe
    image: rl404/image-randomizer:fe-latest
    build: ./frontend
    restart: unless-stopped
    env_file: ./frontend/.env
    network_mode: host
    depends_on:
      - image-randomizer-be
  image-randomizer-be:
    container_name: image-randomizer-be
    image: rl404/image-randomizer:be-latest
    build:
      context: ./backend
      dockerfile: ./build/package/Dockerfile
    command: ./image-randomizer server
    restart: unless-stopped
    network_mode: host
    env_file: ./backend/.env
