version: "2.4"

services:
  image-randomizer-migrate:
    container_name: image-randomizer-migrate
    image: rl404/image-randomizer:latest
    command: ./image-randomizer migrate
    env_file: ./../.env
    network_mode: host
