name: push

on: push

jobs:
  push:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go environment
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Build
        run: |
          cd backend/cmd/image-randomizer
          CGO_ENABLED=0 go build -a -installsuffix cgo -mod vendor -o image-randomizer
