name: publish & deploy

on:
  push:
    tags:
      - "v*"

jobs:
  publish_image:
    name: Build and push image-randomizer image
    runs-on: ubuntu-latest
    outputs:
      img_tag: ${{ steps.tag.outputs.img_tag }}
    steps:
      - name: Check out code
        uses: actions/checkout@v5
      - name: Remove 'v' from tag
        id: tag
        env:
          github_ref: ${{ github.ref }}
        run: |
          github_ref=${github_ref##*/}
          github_ref=${github_ref/v/}
          echo "IMG_TAG=${github_ref}" >> $GITHUB_ENV
          echo "img_tag=${github_ref}" >> $GITHUB_OUTPUT
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Auth gcloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
      - name: Setup docker
        run: |
          gcloud --quiet auth configure-docker
      - name: Build and push image backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/build/package/Dockerfile
          push: true
          tags: |
            rl404/image-randomizer:be-latest
            rl404/image-randomizer:be-${{ env.IMG_TAG }}
            ghcr.io/rl404/image-randomizer:be-latest
            ghcr.io/rl404/image-randomizer:be-${{ env.IMG_TAG }}
            ${{ secrets.GCR_HOSTNAME }}/${{ secrets.GCP_PROJECT_ID }}/image-randomizer:be-${{ env.IMG_TAG }}
      - name: Build and push image frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            rl404/image-randomizer:fe-latest
            rl404/image-randomizer:fe-${{ env.IMG_TAG }}
            ghcr.io/rl404/image-randomizer:fe-latest
            ghcr.io/rl404/image-randomizer:fe-${{ env.IMG_TAG }}
  deploy:
    name: Deploy
    needs: publish_image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/deployment/terraform
    steps:
      - uses: actions/checkout@v5
      - name: Auth gcloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Setup Terraform Variables
        run: |-
          cat > pipeline.auto.tfvars <<EOF
          gcp_project_id          = "${{ secrets.GCP_PROJECT_ID }}"
          gcp_region              = "${{ secrets.GCP_REGION }}"
          gcr_image_name          = "${{ secrets.GCR_HOSTNAME }}/${{ secrets.GCP_PROJECT_ID }}/image-randomizer:be-${{ needs.publish_image.outputs.img_tag }}"
          cloud_run_name          = "${{ secrets.CLOUD_RUN_NAME }}"
          cloud_run_location      = "${{ secrets.CLOUD_RUN_LOCATION }}"
          ir_cache_dialect        = "${{ secrets.IR_CACHE_DIALECT }}"
          ir_cache_address        = "${{ secrets.IR_CACHE_ADDRESS }}"
          ir_cache_password       = "${{ secrets.IR_CACHE_PASSWORD }}"
          ir_cache_time           = "${{ secrets.IR_CACHE_TIME }}"
          ir_db_address           = "${{ secrets.IR_DB_ADDRESS }}"
          ir_db_name              = "${{ secrets.IR_DB_NAME }}"
          ir_db_user              = "${{ secrets.IR_DB_USER }}"
          ir_db_password          = "${{ secrets.IR_DB_PASSWORD }}"
          ir_jwt_access_secret    = "${{ secrets.IR_JWT_ACCESS_SECRET }}"
          ir_jwt_access_expired   = "${{ secrets.IR_JWT_ACCESS_EXPIRED }}"
          ir_jwt_refresh_secret   = "${{ secrets.IR_JWT_REFRESH_SECRET }}"
          ir_jwt_refresh_expired  = "${{ secrets.IR_JWT_REFRESH_EXPIRED }}"
          ir_log_json             = "${{ secrets.IR_LOG_JSON }}"
          ir_log_level            = "${{ secrets.IR_LOG_LEVEL }}"
          ir_newrelic_license_key = "${{ secrets.IR_NEWRELIC_LICENSE_KEY }}"
          EOF
      - name: Init Terraform
        run: terraform init -backend-config "bucket=${{ secrets.GCS_BUCKET }}"
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      - name: Format Terraform
        run: terraform fmt -check
      - name: Plan Terraform
        run: terraform plan -input=false
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      - name: Apply Terraform
        run: terraform apply -auto-approve -input=false
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
