name: publish

on:
  push:
    tags:
      - '*'
jobs:
  publish_image:
    name: Build and push image-randomizer image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Remove 'v' from tag
        env:
          github_ref: ${{ github.ref }}
        run: |
          github_ref=${github_ref##*/}
          github_ref=${github_ref/v/}
          echo "IMG_TAG=${github_ref}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image backend
        uses: docker/build-push-action@v3
        with:
          context: ./backend
          file: ./backend/build/package/Dockerfile
          push: true
          tags: |
            rl404/image-randomizer:be-latest
            rl404/image-randomizer:be-${{ env.IMG_TAG }}
            ghcr.io/rl404/image-randomizer:be-latest
            ghcr.io/rl404/image-randomizer:be-${{ env.IMG_TAG }}
      - name: Build and push image frontend
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            rl404/image-randomizer:fe-latest
            rl404/image-randomizer:fe-${{ env.IMG_TAG }}
            ghcr.io/rl404/image-randomizer:fe-latest
            ghcr.io/rl404/image-randomizer:fe-${{ env.IMG_TAG }}
